// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdata_mover.h"

extern XData_mover_Config XData_mover_ConfigTable[];

XData_mover_Config *XData_mover_LookupConfig(u16 DeviceId) {
	XData_mover_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDATA_MOVER_NUM_INSTANCES; Index++) {
		if (XData_mover_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XData_mover_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XData_mover_Initialize(XData_mover *InstancePtr, u16 DeviceId) {
	XData_mover_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XData_mover_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XData_mover_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

