// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "rx_axis_words7131.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic rx_axis_words7131::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic rx_axis_words7131::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> rx_axis_words7131::ap_ST_fsm_state1 = "1";
const sc_lv<5> rx_axis_words7131::ap_ST_fsm_state2 = "10";
const sc_lv<5> rx_axis_words7131::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<5> rx_axis_words7131::ap_ST_fsm_pp0_stage1 = "1000";
const sc_lv<5> rx_axis_words7131::ap_ST_fsm_state6 = "10000";
const sc_lv<32> rx_axis_words7131::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool rx_axis_words7131::ap_const_boolean_1 = true;
const sc_lv<32> rx_axis_words7131::ap_const_lv32_2 = "10";
const bool rx_axis_words7131::ap_const_boolean_0 = false;
const sc_lv<1> rx_axis_words7131::ap_const_lv1_0 = "0";
const sc_lv<32> rx_axis_words7131::ap_const_lv32_3 = "11";
const sc_lv<32> rx_axis_words7131::ap_const_lv32_1 = "1";
const sc_lv<1> rx_axis_words7131::ap_const_lv1_1 = "1";
const sc_lv<10> rx_axis_words7131::ap_const_lv10_0 = "0000000000";
const sc_lv<64> rx_axis_words7131::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<13> rx_axis_words7131::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<11> rx_axis_words7131::ap_const_lv11_400 = "10000000000";
const sc_lv<10> rx_axis_words7131::ap_const_lv10_200 = "1000000000";
const sc_lv<10> rx_axis_words7131::ap_const_lv10_1 = "1";
const sc_lv<11> rx_axis_words7131::ap_const_lv11_0 = "00000000000";
const sc_lv<11> rx_axis_words7131::ap_const_lv11_7FF = "11111111111";
const sc_lv<11> rx_axis_words7131::ap_const_lv11_7FE = "11111111110";
const sc_lv<9> rx_axis_words7131::ap_const_lv9_0 = "000000000";
const sc_lv<32> rx_axis_words7131::ap_const_lv32_4 = "100";

rx_axis_words7131::rx_axis_words7131(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_predicate_op52_read_state3 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_predicate_op52_read_state3 );

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_predicate_op59_read_state4 );

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_predicate_op59_read_state4 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1_out_full_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_predicate_op52_read_state3 );

    SC_METHOD(thread_ap_block_state4_pp0_stage1_iter0);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_predicate_op59_read_state4 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_143);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_ap_condition_181);
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( tmp_5_i_i_i_i_i_reg_345 );
    sensitive << ( tmp_6_1_i_i_i_i_i_reg_354 );

    SC_METHOD(thread_ap_condition_89);
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( tmp_5_i_i_i_i_i_reg_345 );
    sensitive << ( tmp_6_1_i_i_i_i_i_reg_354 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond1_i_i_i_i_i_fu_249_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( i_i_i_i_i_i_reg_178 );
    sensitive << ( i_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( tmp_5_i_i_i_i_i_reg_345 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( axi_word_V_1_i_i_i_i_fu_298_p3 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190);

    SC_METHOD(thread_ap_predicate_op52_read_state3);
    sensitive << ( exitcond1_i_i_i_i_i_fu_249_p2 );
    sensitive << ( tmp_5_i_i_i_i_i_fu_264_p2 );

    SC_METHOD(thread_ap_predicate_op59_read_state4);
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( tmp_5_i_i_i_i_i_reg_345 );
    sensitive << ( tmp_6_1_i_i_i_i_i_reg_354 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_reg_326 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_axi_word_V_1_i_i_i_i_fu_298_p3);
    sensitive << ( tmp_V_reg_349 );
    sensitive << ( ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190 );

    SC_METHOD(thread_axis_V_V_TDATA_blk_n);
    sensitive << ( axis_V_V_TVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond1_i_i_i_i_i_fu_249_p2 );
    sensitive << ( tmp_5_i_i_i_i_i_fu_264_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( tmp_5_i_i_i_i_i_reg_345 );
    sensitive << ( tmp_6_1_i_i_i_i_i_reg_354 );

    SC_METHOD(thread_axis_V_V_TREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_predicate_op52_read_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_predicate_op59_read_state4 );
    sensitive << ( ap_block_pp0_stage1_11001 );

    SC_METHOD(thread_cache_V1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_7_i_i_i_i_i_fu_306_p1 );

    SC_METHOD(thread_cache_V1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_cache_V1_d0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4 );

    SC_METHOD(thread_cache_V1_we0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond1_i_i_i_i_i_reg_336 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_data_length_V_1_1_i_s_fu_282_p2);
    sensitive << ( p_098_1_i_i_i_i_i_fu_110 );

    SC_METHOD(thread_data_length_V_1_i_i_s_fu_270_p2);
    sensitive << ( p_098_1_i_i_i_i_i_fu_110 );

    SC_METHOD(thread_exitcond1_i_i_i_i_i_fu_249_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4 );

    SC_METHOD(thread_final_burst_length_V_4_fu_237_p3);
    sensitive << ( final_burst_length_V );
    sensitive << ( tmp_i_i_i_i_i_reg_331 );

    SC_METHOD(thread_i_fu_255_p2);
    sensitive << ( ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4 );

    SC_METHOD(thread_lhs_V_cast_i_i_i_i_i_fu_217_p1);
    sensitive << ( loop_count_V );

    SC_METHOD(thread_r_V_fu_221_p2);
    sensitive << ( lhs_V_cast_i_i_i_i_i_fu_217_p1 );

    SC_METHOD(thread_rx_buffer_V_offset1_out_blk_n);
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rx_buffer_V_offset1_out_din);
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1 );
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rx_buffer_V_offset1_out_write);
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rx_buffer_V_offset_out_blk_n);
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rx_buffer_V_offset_out_din);
    sensitive << ( rx_buffer_V_offset );
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_rx_buffer_V_offset_out_write);
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_tmp_5_i_i_i_i_i_fu_264_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_i_i_i_fu_249_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( p_098_1_i_i_i_i_i_fu_110 );

    SC_METHOD(thread_tmp_6_1_i_i_i_i_i_fu_276_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_predicate_op52_read_state3 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( data_length_V_1_i_i_s_fu_270_p2 );

    SC_METHOD(thread_tmp_7_i_i_i_i_i_fu_306_p1);
    sensitive << ( i_i_i_i_i_i_reg_178 );

    SC_METHOD(thread_tmp_cast_i_i_i_i_i_fu_227_p1);
    sensitive << ( tmp_fu_213_p1 );

    SC_METHOD(thread_tmp_fu_213_p1);
    sensitive << ( val_assign );

    SC_METHOD(thread_tmp_i_i_i_i_i_fu_231_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( tmp_cast_i_i_i_i_i_fu_227_p1 );
    sensitive << ( r_V_fu_221_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rx_buffer_V_offset_out_full_n );
    sensitive << ( rx_buffer_V_offset1_out_full_n );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( exitcond1_i_i_i_i_i_fu_249_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "rx_axis_words7131_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, axis_V_V_TDATA, "(port)axis_V_V_TDATA");
    sc_trace(mVcdFile, axis_V_V_TVALID, "(port)axis_V_V_TVALID");
    sc_trace(mVcdFile, axis_V_V_TREADY, "(port)axis_V_V_TREADY");
    sc_trace(mVcdFile, loop_count_V, "(port)loop_count_V");
    sc_trace(mVcdFile, final_burst_length_V, "(port)final_burst_length_V");
    sc_trace(mVcdFile, val_assign, "(port)val_assign");
    sc_trace(mVcdFile, cache_V1_address0, "(port)cache_V1_address0");
    sc_trace(mVcdFile, cache_V1_ce0, "(port)cache_V1_ce0");
    sc_trace(mVcdFile, cache_V1_we0, "(port)cache_V1_we0");
    sc_trace(mVcdFile, cache_V1_d0, "(port)cache_V1_d0");
    sc_trace(mVcdFile, rx_buffer_V_offset, "(port)rx_buffer_V_offset");
    sc_trace(mVcdFile, rx_buffer_V_offset_out_din, "(port)rx_buffer_V_offset_out_din");
    sc_trace(mVcdFile, rx_buffer_V_offset_out_full_n, "(port)rx_buffer_V_offset_out_full_n");
    sc_trace(mVcdFile, rx_buffer_V_offset_out_write, "(port)rx_buffer_V_offset_out_write");
    sc_trace(mVcdFile, rx_buffer_V_offset1, "(port)rx_buffer_V_offset1");
    sc_trace(mVcdFile, rx_buffer_V_offset1_out_din, "(port)rx_buffer_V_offset1_out_din");
    sc_trace(mVcdFile, rx_buffer_V_offset1_out_full_n, "(port)rx_buffer_V_offset1_out_full_n");
    sc_trace(mVcdFile, rx_buffer_V_offset1_out_write, "(port)rx_buffer_V_offset1_out_write");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, axis_V_V_TDATA_blk_n, "axis_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond1_i_i_i_i_i_fu_249_p2, "exitcond1_i_i_i_i_i_fu_249_p2");
    sc_trace(mVcdFile, tmp_5_i_i_i_i_i_fu_264_p2, "tmp_5_i_i_i_i_i_fu_264_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, exitcond1_i_i_i_i_i_reg_336, "exitcond1_i_i_i_i_i_reg_336");
    sc_trace(mVcdFile, tmp_5_i_i_i_i_i_reg_345, "tmp_5_i_i_i_i_i_reg_345");
    sc_trace(mVcdFile, tmp_6_1_i_i_i_i_i_reg_354, "tmp_6_1_i_i_i_i_i_reg_354");
    sc_trace(mVcdFile, rx_buffer_V_offset_out_blk_n, "rx_buffer_V_offset_out_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, rx_buffer_V_offset1_out_blk_n, "rx_buffer_V_offset1_out_blk_n");
    sc_trace(mVcdFile, i_i_i_i_i_i_reg_178, "i_i_i_i_i_i_reg_178");
    sc_trace(mVcdFile, tmp_fu_213_p1, "tmp_fu_213_p1");
    sc_trace(mVcdFile, tmp_reg_326, "tmp_reg_326");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_i_i_i_i_i_fu_231_p2, "tmp_i_i_i_i_i_fu_231_p2");
    sc_trace(mVcdFile, tmp_i_i_i_i_i_reg_331, "tmp_i_i_i_i_i_reg_331");
    sc_trace(mVcdFile, ap_predicate_op52_read_state3, "ap_predicate_op52_read_state3");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_255_p2, "i_fu_255_p2");
    sc_trace(mVcdFile, i_reg_340, "i_reg_340");
    sc_trace(mVcdFile, tmp_V_reg_349, "tmp_V_reg_349");
    sc_trace(mVcdFile, tmp_6_1_i_i_i_i_i_fu_276_p2, "tmp_6_1_i_i_i_i_i_fu_276_p2");
    sc_trace(mVcdFile, ap_predicate_op59_read_state4, "ap_predicate_op59_read_state4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage1_iter0, "ap_block_state4_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4, "ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190, "ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190, "ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190");
    sc_trace(mVcdFile, ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4, "ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4");
    sc_trace(mVcdFile, axi_word_V_1_i_i_i_i_fu_298_p3, "axi_word_V_1_i_i_i_i_fu_298_p3");
    sc_trace(mVcdFile, tmp_7_i_i_i_i_i_fu_306_p1, "tmp_7_i_i_i_i_i_fu_306_p1");
    sc_trace(mVcdFile, p_098_1_i_i_i_i_i_fu_110, "p_098_1_i_i_i_i_i_fu_110");
    sc_trace(mVcdFile, final_burst_length_V_4_fu_237_p3, "final_burst_length_V_4_fu_237_p3");
    sc_trace(mVcdFile, data_length_V_1_1_i_s_fu_282_p2, "data_length_V_1_1_i_s_fu_282_p2");
    sc_trace(mVcdFile, data_length_V_1_i_i_s_fu_270_p2, "data_length_V_1_i_i_s_fu_270_p2");
    sc_trace(mVcdFile, lhs_V_cast_i_i_i_i_i_fu_217_p1, "lhs_V_cast_i_i_i_i_i_fu_217_p1");
    sc_trace(mVcdFile, tmp_cast_i_i_i_i_i_fu_227_p1, "tmp_cast_i_i_i_i_i_fu_227_p1");
    sc_trace(mVcdFile, r_V_fu_221_p2, "r_V_fu_221_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_89, "ap_condition_89");
    sc_trace(mVcdFile, ap_condition_181, "ap_condition_181");
    sc_trace(mVcdFile, ap_condition_143, "ap_condition_143");
#endif

    }
}

rx_axis_words7131::~rx_axis_words7131() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void rx_axis_words7131::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()) && 
             ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
               esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read())) || 
              (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
               esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                     esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                     esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_condition_143.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_condition_181.read(), ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_89.read(), ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190 = axis_V_V_TDATA.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190 = ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190.read();
        }
    }
    if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i_i_i_i_i_i_reg_178 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_i_i_i_i_i_reg_178 = i_reg_340.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_fu_264_p2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_6_1_i_i_i_i_i_fu_276_p2.read(), ap_const_lv1_1))) {
        p_098_1_i_i_i_i_i_fu_110 = data_length_V_1_i_i_s_fu_270_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_fu_264_p2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_1_i_i_i_i_i_fu_276_p2.read()))) {
        p_098_1_i_i_i_i_i_fu_110 = data_length_V_1_1_i_s_fu_282_p2.read();
    } else if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        p_098_1_i_i_i_i_i_fu_110 = final_burst_length_V_4_fu_237_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond1_i_i_i_i_i_reg_336 = exitcond1_i_i_i_i_i_fu_249_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_reg_340 = i_fu_255_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_5_i_i_i_i_i_reg_345 = tmp_5_i_i_i_i_i_fu_264_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_6_1_i_i_i_i_i_reg_354 = tmp_6_1_i_i_i_i_i_fu_276_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_V_reg_349 = axis_V_V_TDATA.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_i_i_i_i_i_reg_331 = tmp_i_i_i_i_i_fu_231_p2.read();
        tmp_reg_326 = tmp_fu_213_p1.read();
    }
}

void rx_axis_words7131::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void rx_axis_words7131::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[3];
}

void rx_axis_words7131::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void rx_axis_words7131::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void rx_axis_words7131::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void rx_axis_words7131::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rx_axis_words7131::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()));
}

void rx_axis_words7131::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()));
}

void rx_axis_words7131::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rx_axis_words7131::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state4.read()));
}

void rx_axis_words7131::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state4.read()));
}

void rx_axis_words7131::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void rx_axis_words7131::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0));
}

void rx_axis_words7131::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()));
}

void rx_axis_words7131::thread_ap_block_state4_pp0_stage1_iter0() {
    ap_block_state4_pp0_stage1_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, axis_V_V_TVALID.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state4.read()));
}

void rx_axis_words7131::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void rx_axis_words7131::thread_ap_condition_143() {
    ap_condition_143 = (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0));
}

void rx_axis_words7131::thread_ap_condition_181() {
    ap_condition_181 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_reg_345.read()) && esl_seteq<1,1,1>(tmp_6_1_i_i_i_i_i_reg_354.read(), ap_const_lv1_1));
}

void rx_axis_words7131::thread_ap_condition_89() {
    ap_condition_89 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_reg_345.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_1_i_i_i_i_i_reg_354.read()));
}

void rx_axis_words7131::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void rx_axis_words7131::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void rx_axis_words7131::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4 = i_reg_340.read();
    } else {
        ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4 = i_i_i_i_i_i_reg_178.read();
    }
}

void rx_axis_words7131::thread_ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_reg_345.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4 = axi_word_V_1_i_i_i_i_fu_298_p3.read();
    } else {
        ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4 = ap_const_lv64_0;
    }
}

void rx_axis_words7131::thread_ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190() {
    ap_phi_reg_pp0_iter0_p_1_1_i_i_i_i_i_reg_190 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void rx_axis_words7131::thread_ap_predicate_op52_read_state3() {
    ap_predicate_op52_read_state3 = (esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_fu_264_p2.read()));
}

void rx_axis_words7131::thread_ap_predicate_op59_read_state4() {
    ap_predicate_op59_read_state4 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_reg_345.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_1_i_i_i_i_i_reg_354.read()));
}

void rx_axis_words7131::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_ap_return() {
    ap_return = esl_concat<11,9>(tmp_reg_326.read(), ap_const_lv9_0);
}

void rx_axis_words7131::thread_axi_word_V_1_i_i_i_i_fu_298_p3() {
    axi_word_V_1_i_i_i_i_fu_298_p3 = esl_concat<32,32>(ap_phi_reg_pp0_iter1_p_1_1_i_i_i_i_i_reg_190.read(), tmp_V_reg_349.read());
}

void rx_axis_words7131::thread_axis_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_fu_264_p2.read())) || 
         (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_i_i_i_i_i_reg_345.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_6_1_i_i_i_i_i_reg_354.read())))) {
        axis_V_V_TDATA_blk_n = axis_V_V_TVALID.read();
    } else {
        axis_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void rx_axis_words7131::thread_axis_V_V_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op52_read_state3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_boolean_1, ap_predicate_op59_read_state4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)))) {
        axis_V_V_TREADY = ap_const_logic_1;
    } else {
        axis_V_V_TREADY = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_cache_V1_address0() {
    cache_V1_address0 =  (sc_lv<9>) (tmp_7_i_i_i_i_i_fu_306_p1.read());
}

void rx_axis_words7131::thread_cache_V1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        cache_V1_ce0 = ap_const_logic_1;
    } else {
        cache_V1_ce0 = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_cache_V1_d0() {
    cache_V1_d0 = ap_phi_mux_p_094_1_i_i_i_i_i_phi_fu_205_p4.read();
}

void rx_axis_words7131::thread_cache_V1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_i_i_i_i_i_reg_336.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        cache_V1_we0 = ap_const_logic_1;
    } else {
        cache_V1_we0 = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_data_length_V_1_1_i_s_fu_282_p2() {
    data_length_V_1_1_i_s_fu_282_p2 = (!p_098_1_i_i_i_i_i_fu_110.read().is_01() || !ap_const_lv11_7FE.is_01())? sc_lv<11>(): (sc_biguint<11>(p_098_1_i_i_i_i_i_fu_110.read()) + sc_bigint<11>(ap_const_lv11_7FE));
}

void rx_axis_words7131::thread_data_length_V_1_i_i_s_fu_270_p2() {
    data_length_V_1_i_i_s_fu_270_p2 = (!p_098_1_i_i_i_i_i_fu_110.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<11>(): (sc_biguint<11>(p_098_1_i_i_i_i_i_fu_110.read()) + sc_bigint<11>(ap_const_lv11_7FF));
}

void rx_axis_words7131::thread_exitcond1_i_i_i_i_i_fu_249_p2() {
    exitcond1_i_i_i_i_i_fu_249_p2 = (!ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4.read().is_01() || !ap_const_lv10_200.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4.read() == ap_const_lv10_200);
}

void rx_axis_words7131::thread_final_burst_length_V_4_fu_237_p3() {
    final_burst_length_V_4_fu_237_p3 = (!tmp_i_i_i_i_i_reg_331.read()[0].is_01())? sc_lv<11>(): ((tmp_i_i_i_i_i_reg_331.read()[0].to_bool())? final_burst_length_V.read(): ap_const_lv11_400);
}

void rx_axis_words7131::thread_i_fu_255_p2() {
    i_fu_255_p2 = (!ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(ap_phi_mux_i_i_i_i_i_i_phi_fu_182_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void rx_axis_words7131::thread_lhs_V_cast_i_i_i_i_i_fu_217_p1() {
    lhs_V_cast_i_i_i_i_i_fu_217_p1 = esl_zext<13,12>(loop_count_V.read());
}

void rx_axis_words7131::thread_r_V_fu_221_p2() {
    r_V_fu_221_p2 = (!ap_const_lv13_1FFF.is_01() || !lhs_V_cast_i_i_i_i_i_fu_217_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(ap_const_lv13_1FFF) + sc_biguint<13>(lhs_V_cast_i_i_i_i_i_fu_217_p1.read()));
}

void rx_axis_words7131::thread_rx_buffer_V_offset1_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        rx_buffer_V_offset1_out_blk_n = rx_buffer_V_offset1_out_full_n.read();
    } else {
        rx_buffer_V_offset1_out_blk_n = ap_const_logic_1;
    }
}

void rx_axis_words7131::thread_rx_buffer_V_offset1_out_din() {
    rx_buffer_V_offset1_out_din = rx_buffer_V_offset1.read();
}

void rx_axis_words7131::thread_rx_buffer_V_offset1_out_write() {
    if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        rx_buffer_V_offset1_out_write = ap_const_logic_1;
    } else {
        rx_buffer_V_offset1_out_write = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_rx_buffer_V_offset_out_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        rx_buffer_V_offset_out_blk_n = rx_buffer_V_offset_out_full_n.read();
    } else {
        rx_buffer_V_offset_out_blk_n = ap_const_logic_1;
    }
}

void rx_axis_words7131::thread_rx_buffer_V_offset_out_din() {
    rx_buffer_V_offset_out_din = rx_buffer_V_offset.read();
}

void rx_axis_words7131::thread_rx_buffer_V_offset_out_write() {
    if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        rx_buffer_V_offset_out_write = ap_const_logic_1;
    } else {
        rx_buffer_V_offset_out_write = ap_const_logic_0;
    }
}

void rx_axis_words7131::thread_tmp_5_i_i_i_i_i_fu_264_p2() {
    tmp_5_i_i_i_i_i_fu_264_p2 = (!p_098_1_i_i_i_i_i_fu_110.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(p_098_1_i_i_i_i_i_fu_110.read() == ap_const_lv11_0);
}

void rx_axis_words7131::thread_tmp_6_1_i_i_i_i_i_fu_276_p2() {
    tmp_6_1_i_i_i_i_i_fu_276_p2 = (!data_length_V_1_i_i_s_fu_270_p2.read().is_01() || !ap_const_lv11_0.is_01())? sc_lv<1>(): sc_lv<1>(data_length_V_1_i_i_s_fu_270_p2.read() == ap_const_lv11_0);
}

void rx_axis_words7131::thread_tmp_7_i_i_i_i_i_fu_306_p1() {
    tmp_7_i_i_i_i_i_fu_306_p1 = esl_zext<64,10>(i_i_i_i_i_i_reg_178.read());
}

void rx_axis_words7131::thread_tmp_cast_i_i_i_i_i_fu_227_p1() {
    tmp_cast_i_i_i_i_i_fu_227_p1 = esl_zext<13,11>(tmp_fu_213_p1.read());
}

void rx_axis_words7131::thread_tmp_fu_213_p1() {
    tmp_fu_213_p1 = val_assign.read().range(11-1, 0);
}

void rx_axis_words7131::thread_tmp_i_i_i_i_i_fu_231_p2() {
    tmp_i_i_i_i_i_fu_231_p2 = (!tmp_cast_i_i_i_i_i_fu_227_p1.read().is_01() || !r_V_fu_221_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_cast_i_i_i_i_i_fu_227_p1.read() == r_V_fu_221_p2.read());
}

void rx_axis_words7131::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(rx_buffer_V_offset1_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rx_buffer_V_offset_out_full_n.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(exitcond1_i_i_i_i_i_fu_249_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage1_subdone.read())) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

