// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _tx_axis_words_HH_
#define _tx_axis_words_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct tx_axis_words : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<9> > cache_V_address0;
    sc_out< sc_logic > cache_V_ce0;
    sc_in< sc_lv<64> > cache_V_q0;
    sc_in< sc_lv<11> > p_read;
    sc_out< sc_lv<32> > axis_V_V_TDATA;
    sc_out< sc_logic > axis_V_V_TVALID;
    sc_in< sc_logic > axis_V_V_TREADY;


    // Module declarations
    tx_axis_words(sc_module_name name);
    SC_HAS_PROCESS(tx_axis_words);

    ~tx_axis_words();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > axis_V_V_TDATA_blk_n;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<1> > exitcond_i_reg_140;
    sc_signal< sc_lv<1> > exitcond_i_reg_140_pp0_iter1_reg;
    sc_signal< sc_lv<11> > i_i_reg_73;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > exitcond_i_fu_84_p2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< sc_logic > ap_sig_ioackin_axis_V_V_TREADY;
    sc_signal< bool > ap_block_state4_io;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<11> > i_fu_89_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > tmp_fu_110_p1;
    sc_signal< sc_lv<1> > tmp_reg_154;
    sc_signal< sc_lv<1> > tmp_reg_154_pp0_iter1_reg;
    sc_signal< sc_lv<64> > axi_word_V_reg_159;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_logic > ap_condition_pp0_exit_iter0_state2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<64> > tmp_5_i_fu_105_p1;
    sc_signal< bool > ap_block_pp0_stage0_01001;
    sc_signal< sc_logic > ap_reg_ioackin_axis_V_V_TREADY;
    sc_signal< sc_lv<10> > tmp_7_cast_i_fu_95_p4;
    sc_signal< sc_lv<6> > op2_assign_fu_114_p3;
    sc_signal< sc_lv<64> > tmp_8_i_fu_121_p1;
    sc_signal< sc_lv<64> > tmp_9_i_fu_125_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_pp0_stage0;
    static const sc_lv<3> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<11> ap_const_lv11_0;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<32> ap_const_lv32_2;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state5();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_01001();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state1();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_io();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_condition_pp0_exit_iter0_state2();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_ap_sig_ioackin_axis_V_V_TREADY();
    void thread_axis_V_V_TDATA();
    void thread_axis_V_V_TDATA_blk_n();
    void thread_axis_V_V_TVALID();
    void thread_cache_V_address0();
    void thread_cache_V_ce0();
    void thread_exitcond_i_fu_84_p2();
    void thread_i_fu_89_p2();
    void thread_op2_assign_fu_114_p3();
    void thread_tmp_5_i_fu_105_p1();
    void thread_tmp_7_cast_i_fu_95_p4();
    void thread_tmp_8_i_fu_121_p1();
    void thread_tmp_9_i_fu_125_p2();
    void thread_tmp_fu_110_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
